# Generated by Django 5.0 on 2024-01-13 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_statement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='others',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='statements.statement'),
        ),
    ]
