# Generated by Django 5.0 on 2024-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_alter_transaction_others_alter_transaction_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
