# Generated by Django 5.0 on 2024-02-03 09:44

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0004_statement_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='statement',
            constraint=models.UniqueConstraint(fields=('month', 'user_id'), name='unique-statement-for-user'),
        ),
    ]
